#!/usr/bin/env python

import cv2 as cv
import numpy as np
import argparse
from cv_bridge import CvBridge, CvBridgeError
import rospy
import intera_interface

def game_state(img):

  return

def main():


if __name__=='__main__':
    main()
